name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make install
      # run: make test
      - run: make lint
      - name: test and publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env: 
          CC_TEST_REPORTER_ID: ${{vars.CC_TEST_REPORTER_ID}}
          XDEBUG_MODE: coverage
        with: 
          coverageCommand: make test
          #coverageLocations: ${{github.workspace}}/reports/clover.xml
          debug: true